/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FunctionManager;
import static View.WordUI.fileText;
import Model.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Joseph Salas
 */
public class WordUI extends javax.swing.JFrame {

    public static String fileText;
    private String printFile;
    private FunctionManager fm = FunctionManager.getInstance();
    private Model.Process ps;
    public static int processCounter;
    public static String sourcePath;
    /**
     * Creates new form WordUI
     */
    public WordUI() {
        initComponents();
        ps = fm.createImplicitProcess(processCounter, SynchronizationType.NONBLOCKING, QueueType.FIFO, 10, SynchronizationType.NONBLOCKING);
        printButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileArea = new javax.swing.JTextArea();
        saveBtn = new javax.swing.JButton();
        printHelp = new javax.swing.JLabel();
        saveHelp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        printButton.setText("Imprimir");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        fileArea.setColumns(20);
        fileArea.setRows(5);
        jScrollPane1.setViewportView(fileArea);
        fileArea.setText(fileText);

        saveBtn.setText("Guardar");
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
        });
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        printHelp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printHelp.setForeground(new java.awt.Color(255, 0, 0));
        printHelp.setText("?");
        printHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printHelpMouseClicked(evt);
            }
        });

        saveHelp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveHelp.setForeground(new java.awt.Color(255, 0, 0));
        saveHelp.setText("?");
        saveHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveHelpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(printHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printButton)
                    .addComponent(saveBtn)
                    .addComponent(printHelp)
                    .addComponent(saveHelp))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed

        printFile = fileArea.getText();
        try {
            fm.sendIndirectProcess(ps.getId(), 1, MessageType.FIXED, 100, sourcePath, -1);
        } catch (InterruptedException ex) {
            Logger.getLogger(WordUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_printButtonActionPerformed

    private void printHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printHelpMouseClicked
       JOptionPane.showMessageDialog(null, "Activa la simulación de impresión donde el archivo entra a una cola de mensajes que sera recibida por la impresora cuando \n"
               + "esta finalice de imprimir el mensaje anterior"
                    , "Información - Imprimir archivo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_printHelpMouseClicked

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnMouseClicked

    private void saveHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveHelpMouseClicked
               JOptionPane.showMessageDialog(null, "Salva el archivo a una carpeta destino"
                    , "Información - Guardar archivo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_saveHelpMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
    
        JFileChooser save = new JFileChooser();
        save.showSaveDialog(null);
        save.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        File file = save.getSelectedFile();
        sourcePath = file.getAbsolutePath();
        System.out.println(sourcePath);
        try {
            saveFile(fileArea.getText(), file);
        } catch (IOException ex) {
            Logger.getLogger(WordUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        printButton.setVisible(true);
        printButton.update(this.getGraphics());
    }//GEN-LAST:event_saveBtnActionPerformed

    
    public void saveFile(String message, File file) throws IOException
    {
        FileWriter write;
       write = new FileWriter(file, true);
        write.write(message);
        write.close();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        fileText = args[0];
        processCounter = Integer.parseInt(args[1]);
        sourcePath = args[2];
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {     
                new WordUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea fileArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel printHelp;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel saveHelp;
    // End of variables declaration//GEN-END:variables
}
